version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/www:/var/www/html
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:8080"
    environment:
      - CHOKIDAR_USERPOLLING=true
    networks:
      - webnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data:
